ScholarMate.Web/Areas/Schools/Controllers/FeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ScholarMate.Infrastructures;
using ScholarMate.Model.Models;
using ScholarMate.Model.Models.Fees;

namespace ScholarMate.Web.Areas.Schools.Controllers
{
    [Area("Schools")]
    public class FeesController : BaseController
    {

        public FeesController(ScholarMateContext ctx) 
            : base(ctx)
        {
        }

        // GET: Schools/Fees
        public async Task<IActionResult> Index()
        {
            var scholarMateContext = _ctx.Fees.Include(f => f.AcademicYear).Include(f => f.School);
            return View(await scholarMateContext.ToListAsync());
        }

        // GET: Schools/Fees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fee = await _ctx.Fees
                .Include(f => f.AcademicYear)
                .Include(f => f.School)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (fee == null)
            {
                return NotFound();
            }

            return View(fee);
        }

        // GET: Schools/Fees/Create
        public IActionResult Create(bool? showInactive)
        {
            //for new fee, use all fee items in the itemize list.
            var feeItems = !showInactive.HasValue || !showInactive.Value ? _ctx.FeeItems.Where(x => x.Active) : _ctx.FeeItems;
            var fee = new Fee { FeeItems = new HashSet<FeeItemMap>() };
            fee.FeeItems = (from it in feeItems.OrderBy(o => o.SortIndex)
                              select new FeeItemMap
                              {
                                  FeeItemId = it.Id,
                                  FeeItem = it,
                                  SortIndex = it.SortIndex
                              }).ToHashSet();

            ViewData["AcademicYearId"] = new SelectList(_ctx.AcademicYears, "Id", "Name");
            return View(fee);
        }

        // POST: Schools/Fees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SchoolId,AcademicYearId,Name")] Fee fee, [Bind("FeeId, FeeItemId,Amount,SortIndex")] ICollection<FeeItemMap> FeeItemMaps)
        {
            if (ModelState.IsValid)
            {
                fee.FeeItems = new HashSet<FeeItemMap>();
                fee.CreatedOn = DateTime.Now;
                fee.UpdatedOn = DateTime.Now;
                foreach (var item in FeeItemMaps)
                {
                    item.CreatedOn = DateTime.Now;
                    item.UpdatedOn = DateTime.Now;
                    item.SchoolId = fee.SchoolId;
                    fee.FeeItems.Add(item);
                }
                _ctx.Add(fee);
                await _ctx.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AcademicYearId"] = new SelectList(_ctx.AcademicYears, "Id", "Name", fee.AcademicYearId);
            return View(fee);
        }

        // GET: Schools/Fees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fee = await _ctx.Fees.Include(x => x.FeeItems)
                .ThenInclude(f => f.FeeItem)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (fee == null)
            {
                return NotFound();
            }
            ViewData["AcademicYearId"] = new SelectList(_ctx.AcademicYears, "Id", "Name", fee.AcademicYearId);
            return View(fee);
        }

        // POST: Schools/Fees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SchoolId,AcademicYearId,Name")] Fee fee, [Bind("Id,FeeId, FeeItemId,Amount,SortIndex")] ICollection<FeeItemMap> FeeItemMaps)
        {
            if (id != fee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //get object from database
                    var eFee = _ctx.Fees.Find(id);

                    //update modelstate object with the appropriate values 
                    eFee.Name = fee.Name;
                    eFee.AcademicYearId = fee.AcademicYearId;
                    eFee.UpdatedOn = DateTime.Now;
                    _ctx.Entry(eFee).State = EntityState.Modified;

                    var strategy = _ctx.Database.CreateExecutionStrategy();
                    await strategy.ExecuteAsync(async () =>
                    {
                        using (var ctrans = _ctx.Database.BeginTransaction())
                        {
                            try
                            {
                                //remove deleted items
                                var dels = _ctx.FeeItemMaps.Where(x => x.FeeId == fee.Id).Except(FeeItemMaps).ToList();
                                _ctx.FeeItemMaps.RemoveRange(dels);
                                foreach (var item in FeeItemMaps)
                                {
                                    var eFeeItem = _ctx.FeeItemMaps.Find(item.Id);
                                    eFeeItem.Amount = item.Amount;
                                    eFeeItem.UpdatedOn = DateTime.Now;
                                    _ctx.Entry(eFeeItem).State = EntityState.Modified;
                                }
                                await _ctx.SaveChangesAsync();
                                ctrans.Commit();
                            }catch(Exception ex) {
                                ctrans.Rollback();
                            }
                        }
                    });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeeExists(fee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AcademicYearId"] = new SelectList(_ctx.AcademicYears, "Id", "Name", fee.AcademicYearId);
            return View(fee);
        }

        // GET: Schools/Fees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fee = await _ctx.Fees
                .Include(f => f.AcademicYear)
                .Include(f => f.School)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (fee == null)
            {
                return NotFound();
            }

            return View(fee);
        }

        // POST: Schools/Fees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fee = await _ctx.Fees.SingleOrDefaultAsync(m => m.Id == id);
            _ctx.Fees.Remove(fee);
            await _ctx.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeeExists(int id)
        {
            return _ctx.Fees.Any(e => e.Id == id);
        }

        // GET: Schools/Fees/FeeItems
        //[NonAction]
        public IActionResult FeeItems(int schoolId, int[] selectedItems)
        {
            var items = _ctx.FeeItems.Where(x => x.SchoolId == schoolId && !selectedItems.Any(y => y == x.Id)).OrderBy(o => o.SortIndex).ThenBy(o => o.Name).Select(x => new { x.Id, x.Name }).ToList();
            return new JsonResult(items);
        }
    }
}

ScholarMate.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ScholarMate.Web.Models;

namespace ScholarMate.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ScholarMate.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

ScholarMate.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ScholarMate.Web/Views/Home/Index.cshtml
@using System.Security.Claims
@using ScholarMate.Web.Extensions


@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron jumbotron-fluid">*@
<h1>ScholarMate</h1>
@*<p class="lead">ScholarMate assists your organization to streamline student registration, fee fixing and arrears, and accounting.</p>*@
@*</div>*@
<div id="carouselExampleIndicators" class="carousel slide my-2" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="carousel-item active">
            <img class="d-block img-fluid" src="~/Images/Carousel/caro1_1200x350.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="~/Images/Carousel/caro2_1200x350.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block img-fluid" src="~/Images/Carousel/caro3_1200x350.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@{
    var schoolid = ((ClaimsIdentity)User.Identity).GetSpecificClaim("SchoolId");
    IDictionary<string, string> all_route = new Dictionary<string, string>();
    all_route.Add("SchoolId", schoolid);
}
@if (User.Identity.IsAuthenticated)
{

    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>Students</h2>
                </div>
                <div class="card-body">
                    <p>
                        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                        enables a clean separation of concerns and gives you full control over markup
                        for enjoyable, agile development.
                    </p>
                    <p><a class="btn btn-primary btn-sm" asp-action="index" asp-controller="Students" asp-all-route-data="all_route" asp-area="Schools">Learn more &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>Academic Years</h2>
                </div>
                <div class="card-body">
                    <p>
                        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                        enables a clean separation of concerns and gives you full control over markup
                        for enjoyable, agile development.
                    </p>
                    <p><a class="btn btn-primary btn-sm" asp-action="index" asp-controller="AcademicYears" asp-all-route-data="all_route" asp-area="Schools">Learn more &raquo;</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>Fees</h2>
                </div>
                <div class="card-body">
                    <p>
                        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                        enables a clean separation of concerns and gives you full control over markup
                        for enjoyable, agile development.
                    </p>
                    <p><a class="btn btn-primary btn-sm" asp-action="index" asp-controller="Fees" asp-all-route-data="all_route" asp-area="Schools">Learn more &raquo;</a></p>
                </div>
            </div>
        </div>
    </div>
}

    <div class="row">
        <div class="col-lg-12">
            <form id="shopping-cart" action="cart.html" method="post">
                <table class="shopping-cart">
                    <thead>
                        <tr>
                            <th scope="col">Item</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table> <p id="sub-total">
                    <strong>
                        Sub
                        Total
                    </strong>: <span id="stotal"></span>
                </p> <ul id="shoppingcart-actions">
                    <li>
                        <input type="submit" name="update" id="updatecart"
                               class="btn" value="Update Cart" />
                    </li>
                    <li>
                        <input type="submit" name="delete" id="empty-cart" class="btn"
                               value="Empty Cart" />
                    </li>
                    <li>
                        <a href="index.html"
                           class="btn">Continue Shopping</a>
                    </li>
                    <li>
                        <a href="checkout.html" class="btn">Go To Checkout</a>
                    </li>
                </ul>
            </form>
        </div>
    </div>